;;; dsh-bridge.el --- Emacs <-> DeepSeek Harness bridge -*- lexical-binding: t; -*-

;; Copyright (C) 2026  Chong Yidong <cyd@stupidchicken.com>
;;
;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;; Author: Chong Yidong <cyd@stupidchicken.com>
;; Version: 0.1.0
;; Package-Requires: ((emacs "29.1"))
;; Keywords: tools, convenience

;;; Commentary:

;; Two-way bridge between Emacs and a running DeepSeek Harness session.  Talks
;; to the `dsh-emacs-bridge' DSH plugin over loopback HTTP.
;;
;; Interface (see emacs-interface-plan.md):
;;   dsh-bridge                     transient dispatcher; header shows the target
;;   dsh-bridge-send / -draft       region-or-buffer -> prompt / composer draft
;;   dsh-bridge-fetch               latest reply -> *dsh-bridge-output*
;;   dsh-bridge-inbox               pull "Send to Emacs" messages -> *dsh-bridge-inbox*
;;   dsh-bridge-prompt              persistent prompt-editing buffer
;;   dsh-bridge-select-session      pin the target session
;;   dsh-bridge-list-sessions       tabulated session browser
;;
;; The bridge targets the last-active session unless one is pinned with
;; `dsh-bridge-select-session'; a prefix argument to send/draft/fetch makes a
;; one-shot session choice for that call only.
;;
;; No global keybinding by default: `C-c <letter>' is reserved for users.  The
;; README documents `(keymap-global-set "C-c d" #'dsh-bridge)'; the Tools >
;; DSH Bridge menu provides key-free access, and the view buffers bind the
;; dispatcher's letters buffer-locally.

;;; Code:

(require 'url)
(require 'url-util)
(require 'url-parse)
(require 'subr-x)
(require 'seq)
(require 'json)
(require 'transient)

(defgroup dsh-bridge nil
  "Emacs <-> DeepSeek Harness bridge."
  :group 'tools)

(defcustom dsh-bridge-url "http://127.0.0.1:3080/dsh-bridge"
  "Base URL of the `dsh-emacs-bridge' HTTP route."
  :type 'string
  :group 'dsh-bridge)

(defcustom dsh-bridge-token-file
  (expand-file-name "dsh-bridge-token"
                    (let ((home (string-trim (or (getenv "DSH_HOME") ""))))
                      (if (string-empty-p home) "~/.dsh" home)))
  "File holding the shared bridge token, generated by the DSH plugin.
The plugin stores it at `$DSH_HOME/dsh-bridge-token' (default
`~/.dsh/dsh-bridge-token').  A relative `$DSH_HOME' resolves against
the `dsh' process's working directory, so set this option explicitly
when using one."
  :type 'file
  :group 'dsh-bridge)

(defcustom dsh-bridge-token nil
  "Bearer token for the bridge, or nil to read `dsh-bridge-token-file'.
When non-nil, this value is sent as `Authorization: Bearer <token>' on every
request."
  :type '(choice (const :tag "Read from file" nil) string)
  :group 'dsh-bridge)

(defcustom dsh-bridge-timeout 5
  "Timeout in seconds for synchronous bridge requests."
  :type 'number
  :group 'dsh-bridge)

(defcustom dsh-bridge-prompt-markdown t
  "Use `markdown-mode' as the parent of `dsh-bridge-prompt-mode' when available.
markdown-mode is not part of Emacs core.  When it is not installed, or this
option is nil, the prompt buffer derives from `text-mode'.  The choice is
resolved when this package is loaded; changing the option takes effect after
reloading."
  :type 'boolean
  :group 'dsh-bridge)

(defcustom dsh-bridge-view-gfm t
  "Use `gfm-view-mode' for the output/inbox view buffers when available.
When non-nil and `gfm-view-mode' is loadable (markdown-mode installed),
`*dsh-bridge-output*' and `*dsh-bridge-inbox*' inherit GitHub-Flavored
Markdown font-locking, native code-block highlighting, and the read-only view
keymap; otherwise they fall back to `special-mode'."
  :type 'boolean
  :group 'dsh-bridge)

(defcustom dsh-bridge-notifications t
  "When non-nil, subscribe to bridge push notifications.
Emacs opens a loopback connection to the bridge's event stream and, when the
DSH web UI's \"Send to Emacs\" button deposits a message, pulls it into
`*dsh-bridge-inbox*' automatically.  The listener starts lazily on first bridge
use; `dsh-bridge-notifications-start' / `-stop' control it."
  :type 'boolean
  :group 'dsh-bridge)

(defcustom dsh-bridge-show-session-ids nil
  "When non-nil, show raw DSH session ids in the sessions list.
Session ids are internal to the bridge; by default the list and the selector
show only friendly labels.  Enable this for debugging."
  :type 'boolean
  :group 'dsh-bridge)

(defcustom dsh-bridge-sessions-show-saved nil
  "When non-nil, `*dsh-bridge-sessions*' also lists saved (cold) sessions.
By default only live sessions are listed; `v' toggles this for the current
buffer."
  :type 'boolean
  :group 'dsh-bridge)

(defvar dsh-bridge-target-session nil
  "DSH session id the bridge targets, or nil for the last-active session.
Set with `dsh-bridge-select-session'.")

(defvar dsh-bridge--sessions-cache nil
  "Last list of session row alists fetched from the host, or nil.
Kept so an id can be turned back into its display label without an extra HTTP
request.")

(defvar-local dsh-bridge--show-saved nil
  "Whether `*dsh-bridge-sessions*' lists saved (cold) sessions.
Initialized from `dsh-bridge-sessions-show-saved' when the buffer is created;
`v' toggles it.")

;;; Low-level HTTP plumbing

(defun dsh-bridge--response-body (buffer)
  "Return the HTTP response body (text after the headers) of BUFFER.
The url-http response buffer is unibyte, so decode the body as UTF-8."
  (with-current-buffer buffer
    (goto-char (point-min))
    (if (re-search-forward "\r?\n\r?\n" nil t)
        (decode-coding-string
         (buffer-substring-no-properties (point) (point-max)) 'utf-8)
      "")))

(defun dsh-bridge--token ()
  "Return the bridge bearer token as a unibyte string, or nil if none.

`insert-file-contents' yields a multibyte string, and a multibyte (even
pure-ASCII) Authorization header value poisons url-http's request
concatenation: when the request body then contains non-ASCII bytes, the
request string becomes multibyte and url-http errors with \"Multibyte
text in HTTP request\" (bug#23750) in the process sentinel — surfacing
only as a request timeout.  The token is hex, so coercing to unibyte is
lossless."
  (let ((token (or dsh-bridge-token
                   (and (file-readable-p dsh-bridge-token-file)
                        (with-temp-buffer
                          (insert-file-contents dsh-bridge-token-file)
                          (string-trim (buffer-string)))))))
    (and token (string-to-unibyte token))))

;;; Push notifications (loopback SSE listener for "Send to Emacs")

(defvar dsh-bridge--notifications-enabled nil
  "Whether the notification listener should stay connected.")

(defvar dsh-bridge--notifications-process nil
  "The live SSE notification process, or nil.")

(defvar dsh-bridge--notifications-timer nil
  "Reconnect timer for the notification listener, or nil.")

(defvar dsh-bridge--notifications-raw ""
  "Raw, not-yet-decoded bytes from the notification process (unibyte).")

(defvar dsh-bridge--notifications-headers-done nil
  "Non-nil once the HTTP response headers have been consumed.")

(defvar dsh-bridge--notifications-sse ""
  "Decoded, not-yet-parsed SSE text from the notification process.")

(defvar dsh-bridge--notifications-inbox-pending nil
  "Non-nil while an inbox pull is already scheduled.")

(defun dsh-bridge--chunked-decode (text)
  "Decode HTTP/1.1 chunked-transfer-encoded TEXT (a unibyte string).
Return (DECODED . REST): DECODED is the decoded body prefix, REST is the raw
trailing text of an incomplete chunk, to be completed by a later call."
  (let ((chunks nil)
        (rest text))
    (catch 'done
      (while t
        (unless (string-match "\\`\\([0-9A-Fa-f]+\\)\r?\n" rest)
          (throw 'done nil))
        (let* ((hex (match-string 1 rest))
               (size (string-to-number hex 16))
               (size-end (match-end 0)))
          (if (= size 0)
              (if (>= (length rest) (+ size-end 2))
                  (progn (setq rest (substring rest (+ size-end 2)))
                         (throw 'done nil))
                (throw 'done nil))
            (let ((data-end (+ size-end size)))
              (if (>= (length rest) (+ data-end 2))
                  (progn (push (substring rest size-end data-end) chunks)
                         (setq rest (substring rest (+ data-end 2))))
                (throw 'done nil)))))))
    (cons (apply #'concat (nreverse chunks)) rest)))

(defun dsh-bridge--sse-parse (text)
  "Parse accumulated SSE TEXT into (EVENTS . REST).
EVENTS is a list of decoded `data:' payloads (alists); REST is the trailing
text with no complete event terminator."
  (let ((events nil)
        (rest text))
    (while (string-match "\\(?:\r?\n\\)\\{2\\}" rest)
      (let ((chunk (substring rest 0 (match-beginning 0))))
        (setq rest (substring rest (match-end 0)))
        (dolist (line (split-string chunk "\r?\n"))
          (when (string-prefix-p "data:" line)
            (let ((json (condition-case nil
                            (json-parse-string (string-trim (substring line 5))
                                               :object-type 'alist
                                               :array-type 'list)
                          (error nil))))
              (when json (push json events)))))))
    (cons (nreverse events) rest)))

(defun dsh-bridge--outbox-notice-p (events)
  "Whether EVENTS (decoded SSE events) contain an outbox notice."
  (seq-some (lambda (e) (equal (alist-get 'kind e) "outbox")) events))

(defun dsh-bridge--notification-inbox ()
  "Pull the inbox once for a pending push notification."
  (setq dsh-bridge--notifications-inbox-pending nil)
  ;; `dsh-bridge-inbox' is defined later in this file; call it via its symbol
  ;; so the byte-compiler does not flag a forward reference.
  (funcall 'dsh-bridge-inbox))

(defun dsh-bridge--notification-filter (_proc string)
  "Process filter for the SSE notification connection: decode and dispatch."
  (setq dsh-bridge--notifications-raw
        (concat dsh-bridge--notifications-raw string))
  (unless dsh-bridge--notifications-headers-done
    (let ((pos (string-match "\r\n\r\n" dsh-bridge--notifications-raw)))
      (when pos
        (setq dsh-bridge--notifications-raw
              (substring dsh-bridge--notifications-raw (+ pos 4)))
        (setq dsh-bridge--notifications-headers-done t))))
  (when dsh-bridge--notifications-headers-done
    (let* ((decoded (dsh-bridge--chunked-decode dsh-bridge--notifications-raw))
           (body (decode-coding-string (car decoded) 'utf-8)))
      (setq dsh-bridge--notifications-raw (cdr decoded))
      (unless (string-empty-p body)
        (setq dsh-bridge--notifications-sse
              (concat dsh-bridge--notifications-sse body))
        (let* ((parsed (dsh-bridge--sse-parse dsh-bridge--notifications-sse))
               (events (car parsed)))
          (setq dsh-bridge--notifications-sse (cdr parsed))
          (when (and events
                     (dsh-bridge--outbox-notice-p events)
                     (not dsh-bridge--notifications-inbox-pending))
            (setq dsh-bridge--notifications-inbox-pending t)
            ;; Defer: `dsh-bridge-inbox' does a synchronous pull that must not
            ;; re-enter this filter via `accept-process-output'.
            (run-at-time 0 nil #'dsh-bridge--notification-inbox)))))))

(defun dsh-bridge--notifications-retry ()
  "Schedule a reconnect attempt for the notification listener."
  (when (and dsh-bridge--notifications-enabled
             (not (timerp dsh-bridge--notifications-timer)))
    (setq dsh-bridge--notifications-timer
          (run-at-time 5 nil #'dsh-bridge-notifications-start))))

(defun dsh-bridge--notification-sentinel (_proc event)
  "Sentinel for the SSE notification process: reconnect on close/error."
  (unless (string-prefix-p "open" event)
    (setq dsh-bridge--notifications-process nil)
    (when dsh-bridge--notifications-enabled
      (dsh-bridge--notifications-retry))))

(defun dsh-bridge--notifications-connect (token)
  "Open the SSE connection and send the subscribe request."
  (let* ((parsed (url-generic-parse-url (concat dsh-bridge-url "/events")))
         (host (url-host parsed))
         (port (url-port parsed)))
    (setq dsh-bridge--notifications-raw "")
    (setq dsh-bridge--notifications-headers-done nil)
    (setq dsh-bridge--notifications-sse "")
    (setq dsh-bridge--notifications-process
          (make-network-process
           :name "dsh-bridge-notifications"
           :host host
           :service port
           :family 'ipv4
           :coding 'binary
           :noquery t
           :filter #'dsh-bridge--notification-filter
           :sentinel #'dsh-bridge--notification-sentinel))
    (process-send-string
     dsh-bridge--notifications-process
     (format "GET %s?token=%s HTTP/1.1\r\nHost: %s:%d\r\nAccept: text/event-stream\r\n\r\n"
             (url-filename parsed) (url-hexify-string token) host port))))

(defun dsh-bridge-notifications-start ()
  "Connect the bridge notification listener (idempotent)."
  (interactive)
  (setq dsh-bridge--notifications-enabled t)
  (when (timerp dsh-bridge--notifications-timer)
    (cancel-timer dsh-bridge--notifications-timer)
    (setq dsh-bridge--notifications-timer nil))
  (unless (and dsh-bridge--notifications-process
               (process-live-p dsh-bridge--notifications-process))
    (let ((token (dsh-bridge--token)))
      (if (null token)
          (dsh-bridge--notifications-retry)
        (condition-case nil
            (dsh-bridge--notifications-connect token)
          (error (dsh-bridge--notifications-retry)))))))

(defun dsh-bridge-notifications-stop ()
  "Stop the bridge notification listener."
  (interactive)
  (setq dsh-bridge--notifications-enabled nil)
  (when (timerp dsh-bridge--notifications-timer)
    (cancel-timer dsh-bridge--notifications-timer)
    (setq dsh-bridge--notifications-timer nil))
  (when (and dsh-bridge--notifications-process
             (process-live-p dsh-bridge--notifications-process))
    (delete-process dsh-bridge--notifications-process))
  (setq dsh-bridge--notifications-process nil))

(defun dsh-bridge--ensure-notifications ()
  "Start the notification listener on first use, when enabled."
  (when (and dsh-bridge-notifications
             (not dsh-bridge--notifications-enabled))
    (dsh-bridge-notifications-start)))

(defun dsh-bridge--extra-headers (payload)
  "Return the HTTP header alist for a request with PAYLOAD (nil for no body).
Always includes the bearer Authorization header when a token is known."
  (let ((token (dsh-bridge--token)))
    (append (and payload '(("Content-Type" . "application/json")))
            (and token (list (cons "Authorization" (concat "Bearer " token)))))))

(defun dsh-bridge--path (path session-id)
  "Return PATH with an optional ?sessionId= query parameter."
  (if session-id
      (format "%s?sessionId=%s" path (url-hexify-string session-id))
    path))

(defun dsh-bridge--error-message (status http-status alist)
  "Return a user-facing error message for a failed request, or nil on success.
STATUS is the url-retrieve status plist, HTTP-STATUS the HTTP status code (or
nil), and ALIST the decoded JSON body (or nil)."
  (let ((transport-error (plist-get status :error)))
    (cond
     (transport-error (format "request failed: %s" transport-error))
     ((and http-status (>= http-status 400))
      (format "HTTP %s: %s" http-status
              (or (alist-get 'error alist) "error")))
     ((and alist (assoc 'error alist)) (alist-get 'error alist))
     (t nil))))

(defun dsh-bridge--call (method path payload callback)
  "Perform METHOD request to PATH under `dsh-bridge-url'.
PAYLOAD is an alist encoded as JSON (for POST) or nil (for GET).
CALLBACK is invoked with (status body-string HTTP-STATUS), where STATUS is nil
on a completed request (whatever the HTTP status) or an `:error' plist on a
transport failure/timeout.  Uses `url-retrieve-synchronously': a request here
is a short loopback round-trip, and the async `url-retrieve' path reports
process-sentinel failures (such as the bug#23750 \"Multibyte text in HTTP
request\" error) only via `message', which made them hard to diagnose."
  (dsh-bridge--ensure-notifications)
  (let ((url-request-method method)
        (url-request-data
         (and payload (encode-coding-string (json-encode payload) 'utf-8)))
        (url-request-extra-headers (dsh-bridge--extra-headers payload)))
    (let ((buf nil)
          (err nil))
      (condition-case e
          (setq buf (url-retrieve-synchronously (concat dsh-bridge-url path)
                                                t nil dsh-bridge-timeout))
        (error (setq err e)))
      (cond
       (err (funcall callback (list :error (error-message-string err)) nil nil))
       ((null buf) (funcall callback '(:error "request timed out") nil nil))
       (t
        (let ((http-status (with-current-buffer buf
                             (and (boundp 'url-http-response-status)
                                  url-http-response-status)))
              (body (dsh-bridge--response-body buf)))
          (kill-buffer buf)
          (funcall callback nil body http-status)))))))

(defun dsh-bridge--request (method path payload)
  "Perform METHOD request to PATH and return (STATUS . ALIST).
STATUS is the HTTP status code, or nil on transport failure.  ALIST is the
decoded JSON object (JSON null/false become nil, arrays become lists), or nil
when the body is not a JSON object."
  (dsh-bridge--ensure-notifications)
  (let ((url-request-method method)
        (url-request-data
         (and payload (encode-coding-string (json-encode payload) 'utf-8)))
        (url-request-extra-headers (dsh-bridge--extra-headers payload)))
    (let ((buf (url-retrieve-synchronously (concat dsh-bridge-url path)
                                           t nil dsh-bridge-timeout)))
      (if (null buf)
          (cons nil nil)
        (with-current-buffer buf
          (let* ((status (and (boundp 'url-http-response-status)
                              url-http-response-status))
                 (body (dsh-bridge--response-body buf))
                 (alist (condition-case nil
                            (json-parse-string body :object-type 'alist
                                               :array-type 'list
                                               :null-object nil
                                               :false-object nil)
                          (error nil))))
            (kill-buffer buf)
            (cons status alist)))))))

(defun dsh-bridge--fetch-sessions ()
  "Return the DSH session list as a list of alists, or nil on error.
Also caches the list in `dsh-bridge--sessions-cache' for id->label lookups."
  (let* ((result (dsh-bridge--request "GET" "/sessions" nil))
         (alist (cdr result))
         (sessions (and alist (assoc 'sessions alist)
                        (cdr (assoc 'sessions alist)))))
    (when sessions
      (setq dsh-bridge--sessions-cache sessions))
    sessions))

(defun dsh-bridge--inbox-header (entry)
  "Return a provenance header line for an outbox ENTRY."
  (format "--- %s%s%s ---"
          (or (alist-get 'source entry) "bridge")
          (let ((sid (alist-get 'sessionId entry)))
            (if sid
                (format " | session %s"
                        (or (dsh-bridge--label-for-id sid) sid))
              ""))
          (let ((ts (alist-get 'ts entry)))
            (if ts (format " | %s"
                           (format-time-string "%Y-%m-%d %H:%M:%S"
                                               (/ ts 1000)))
              ""))))

;;; Session labels

(defun dsh-bridge--session-label (session)
  "Return the display label for SESSION (a row alist).
Mirrors DSH's display title: the session title, else the workspace basename,
else the raw id."
  (or (let ((title (alist-get 'title session)))
        (and (stringp title) (not (string-empty-p title)) title))
      (let ((cwd (alist-get 'cwd session)))
        (and (stringp cwd) (not (string-empty-p cwd))
             (let ((base (file-name-nondirectory (directory-file-name cwd))))
               (and (not (string-empty-p base)) base))))
      (alist-get 'id session)))

(defun dsh-bridge--session-for-id (id)
  "Return the cached session row alist whose id is ID, or nil."
  (seq-find (lambda (s) (equal (alist-get 'id s) id))
            dsh-bridge--sessions-cache))

(defun dsh-bridge--session-live-p (id)
  "Whether the cached session ID is live (has a running agent)."
  (alist-get 'live (dsh-bridge--session-for-id id)))

(defun dsh-bridge--label-for-id (id)
  "Return the display label for session ID, or nil when unknown."
  (let ((session (dsh-bridge--session-for-id id)))
    (and session (dsh-bridge--session-label session))))

(defun dsh-bridge--label-from-response (alist fallback-id)
  "Return a display label from a bridge response ALIST.
Prefers the response's `title' (fresh from the host), then the cached label
of FALLBACK-ID, then FALLBACK-ID itself."
  (or (alist-get 'title alist)
      (and fallback-id
           (or (dsh-bridge--label-for-id fallback-id) fallback-id))))

(defun dsh-bridge--session-activity (session)
  "Return the ms-epoch activity timestamp for SESSION (a row alist).
Live sessions use their last event time; saved sessions their creation time."
  (or (alist-get 'lastActive session) (alist-get 'createdAt session) 0))

(defun dsh-bridge--relative-age (ts &optional now)
  "Return a compact relative age string for ms-epoch timestamp TS.
Matches DSH's own session rows (\"now\", \"5min\", \"3h\", \"2d\", \"4mo\",
\"1y\").  NOW is the reference time in seconds (default: the current time)."
  (let* ((now (or now (float-time)))
         (secs (max 0 (- now (/ ts 1000.0)))))
    (cond
     ((< secs 60) "now")
     ((< secs 3600) (format "%dmin" (floor (/ secs 60))))
     ((< secs 86400) (format "%dh" (floor (/ secs 3600))))
     ((< secs (* 30 86400)) (format "%dd" (floor (/ secs 86400))))
     ((< secs (* 365 86400)) (format "%dmo" (floor (/ secs (* 30 86400)))))
     (t (format "%dy" (floor (/ secs (* 365 86400))))))))

(defun dsh-bridge--workspace-label (session)
  "Return the workspace label for SESSION (a row alist).
The workspace title, else the cwd basename, else the raw cwd (or \"\")."
  (or (let ((ws (alist-get 'workspace session)))
        (and (stringp ws) (not (string-empty-p ws)) ws))
      (let ((cwd (alist-get 'cwd session)))
        (and (stringp cwd) (not (string-empty-p cwd))
             (let ((base (file-name-nondirectory (directory-file-name cwd))))
               (and (not (string-empty-p base)) base))))
      (or (alist-get 'cwd session) "")))

;;; Target helpers

(defun dsh-bridge--target-label ()
  "Label of the current target: the pinned session's label, or \"last-active\"."
  (if dsh-bridge-target-session
      (or (dsh-bridge--label-for-id dsh-bridge-target-session)
          dsh-bridge-target-session)
    "last-active"))

(defun dsh-bridge--target-header ()
  "Header string for the dispatcher: the bridge name plus the target."
  (format "DSH Bridge · target: %s" (dsh-bridge--target-label)))

(defun dsh-bridge--live-session-choices ()
  "Return an alist of (LABEL . ID) for live sessions, or nil."
  (mapcar (lambda (s) (cons (dsh-bridge--session-label s) (alist-get 'id s)))
          (seq-filter (lambda (s) (alist-get 'live s))
                      (dsh-bridge--fetch-sessions))))

(defun dsh-bridge--read-session-override (prompt)
  "With a prefix argument, read a live session for one-shot use.
Returns the chosen session id, or nil without a prefix argument (the caller
then uses the pinned/last-active target)."
  (when current-prefix-arg
    (let ((choices (dsh-bridge--live-session-choices)))
      (if (null choices)
          (user-error "dsh-bridge: no live sessions")
        (cdr (assoc (completing-read prompt choices nil t) choices))))))

(defun dsh-bridge--region-or-buffer ()
  "Return the region text if the region is active, else the whole buffer."
  (if (use-region-p)
      (buffer-substring-no-properties (region-beginning) (region-end))
    (buffer-substring-no-properties (point-min) (point-max))))

;;; Text senders (internal)

(defun dsh-bridge-send-text (text &optional session-id)
  "Send TEXT to the DSH session as a prompt.
SESSION-ID overrides the pinned target for this call only."
  (let* ((target (or session-id dsh-bridge-target-session))
         (payload (append (list (cons 'text text))
                          (and target (list (cons 'sessionId target))))))
    (dsh-bridge--call "POST" "/send" payload
      (lambda (status body http-status)
        (let* ((alist (condition-case nil
                          (json-parse-string body :object-type 'alist)
                        (error nil)))
               (err (dsh-bridge--error-message status http-status alist)))
          (cond
           (err (message "dsh-bridge: %s" err))
           ((null alist)
            (message "dsh-bridge: unreadable response: %s" body))
           (t (message "dsh-bridge: sent to %s"
                       (or (dsh-bridge--label-from-response alist target)
                           "the last-active session")))))))))

(defun dsh-bridge-send-draft (text &optional session-id)
  "Send TEXT to the DSH composer as a draft (not submitted).
SESSION-ID overrides the pinned target for this call only."
  (let* ((target (or session-id dsh-bridge-target-session))
         (payload (append (list (cons 'text text))
                          (and target (list (cons 'sessionId target))))))
    (dsh-bridge--call "POST" "/draft" payload
      (lambda (status body http-status)
        (let* ((alist (condition-case nil
                          (json-parse-string body :object-type 'alist)
                        (error nil)))
               (err (dsh-bridge--error-message status http-status alist)))
          (cond
           (err (message "dsh-bridge: %s" err))
           ((null alist)
            (message "dsh-bridge: unreadable response: %s" body))
           (t (message "dsh-bridge: draft pushed to %s"
                       (or (dsh-bridge--label-from-response alist target)
                           "the active session")))))))))

;;; Shared letter->command table (dispatcher + view buffers)

;; The verb suffixes are the single source of truth for the letter keys: the
;; view buffers' keymap and the dispatcher layout are both derived from it, so
;; they cannot drift apart.  `eval-and-compile' because the transient macro
;; expansion reads the value at compile time.
(eval-and-compile
  (defconst dsh-bridge--verb-suffixes
    '(("s" dsh-bridge-send :description "send region/buffer (prompt)")
      ("d" dsh-bridge-draft :description "send region/buffer (draft)")
      ("f" dsh-bridge-fetch :description "fetch latest reply")
      ("i" dsh-bridge-inbox :description "pull \"Send to Emacs\" messages")
      ("S" dsh-bridge-select-session :description "select session")
      ("l" dsh-bridge-list-sessions :description "list sessions"))
    "Suffix specs shared by the `dsh-bridge' dispatcher and the view buffers.
Each spec is (KEY COMMAND DESCRIPTION).")

  (defconst dsh-bridge--dispatcher-layout
    (vconcat (list :description '(lambda () (dsh-bridge--target-header)))
             dsh-bridge--verb-suffixes
             (list '("p" dsh-bridge-prompt :description "edit prompt buffer")
                   '("q" transient-quit-one :description "quit")))
    "Layout of the `dsh-bridge' dispatcher.
The verb suffixes come from `dsh-bridge--verb-suffixes'; `p' (prompt buffer)
and `q' (quit) are dispatcher-only."))

;;; View buffers (*dsh-bridge-output*, *dsh-bridge-inbox*)

(defvar-local dsh-bridge--view-timestamp nil
  "Time the current view buffer was last refreshed, or nil.")

(defvar-local dsh-bridge--view-content-session nil
  "Session the current view buffer's content came from, or nil.
Set only in `*dsh-bridge-output*': a peek or `C-u' override fills the buffer
with a reply that is not the pinned target's, and the header line must say
so.  The inbox (a global log) leaves this nil and labels the target.")

(defun dsh-bridge--view-header-line ()
  "Header line for the output/inbox buffers: provenance plus refresh time."
  (format "DSH Bridge · %s%s"
          (if dsh-bridge--view-content-session
              (format "reply from: %s"
                      (or (dsh-bridge--label-for-id
                           dsh-bridge--view-content-session)
                          dsh-bridge--view-content-session))
            (format "target: %s" (dsh-bridge--target-label)))
          (if dsh-bridge--view-timestamp
              (format " · refreshed %s" dsh-bridge--view-timestamp)
            "")))

(defun dsh-bridge--prompt-header-line ()
  "Header line for the prompt buffer: the current target."
  (format "DSH Bridge · target: %s" (dsh-bridge--target-label)))

(declare-function gfm-view-mode "markdown-mode")
(declare-function dsh-bridge-view-mode "dsh-bridge")
;; The mode map is created by whichever branch of the `if' runs; declare it here
;; so the byte-compiler knows the `define-key' forms below are valid.
(defvar dsh-bridge-view-mode-map)

(defmacro dsh-bridge--define-view-mode (parent)
  "Define `dsh-bridge-view-mode' as a variant of PARENT.
PARENT is `gfm-view-mode' when markdown-mode is installed, else `special-mode';
the choice is resolved at load time."
  `(define-derived-mode dsh-bridge-view-mode ,parent "DSH-View"
     "Major mode for `*dsh-bridge-output*' and `*dsh-bridge-inbox*'.
Read-only; the letter keys mirror the `dsh-bridge' dispatcher (`s' send,
`d' draft, `f' re-fetch/re-pull, `i' pull inbox, `S' select session, `l' list
sessions), `r' replies, `g' refreshes, `q' quits.  When derived from
`gfm-view-mode' the buffer also gains GitHub-Flavored Markdown font-locking."
     (setq buffer-read-only t)))

(if (and dsh-bridge-view-gfm (require 'markdown-mode nil t) (fboundp 'gfm-view-mode))
    (dsh-bridge--define-view-mode gfm-view-mode)
  (dsh-bridge--define-view-mode special-mode))

;; The dispatcher letters plus refresh/dismiss, always present in the mode keymap.
(dolist (spec dsh-bridge--verb-suffixes)
  (define-key dsh-bridge-view-mode-map (kbd (car spec)) (cadr spec)))
(define-key dsh-bridge-view-mode-map (kbd "g") #'revert-buffer)
(define-key dsh-bridge-view-mode-map (kbd "q") #'quit-window)
(define-key dsh-bridge-view-mode-map (kbd "r") #'dsh-bridge-reply)

(easy-menu-define dsh-bridge-view-menu dsh-bridge-view-mode-map
  "Menu bar menu for the `*dsh-bridge-output*' and `*dsh-bridge-inbox*' buffers."
  '("DSH Bridge"
    ["Send Region/Buffer" dsh-bridge-send
     :help "Send the region (or whole buffer) to DSH as a prompt"]
    ["Send as Draft" dsh-bridge-draft
     :help "Send the region (or whole buffer) to the DSH composer as a draft"]
    ["Fetch Latest Reply" dsh-bridge-fetch
     :help "Fetch the latest assistant reply into *dsh-bridge-output*"]
    ["Pull Inbox" dsh-bridge-inbox
     :help "Pull Send-to-Emacs messages into *dsh-bridge-inbox*"]
    ["Reply" dsh-bridge-reply
     :help "Open the prompt buffer to reply to the shown session"]
    "---"
    ["Select Session…" dsh-bridge-select-session
     :help "Pin the target session"]
    ["List Sessions" dsh-bridge-list-sessions
     :help "Browse DSH sessions"]
    "---"
    ["Refresh" revert-buffer
     :help "Refresh this buffer"]
    ["Quit Window" quit-window
     :help "Dismiss this buffer"]))

(defun dsh-bridge--revert-output (&rest _)
  "Re-fetch the latest reply into the output buffer."
  (dsh-bridge-fetch))

(defun dsh-bridge--revert-inbox (&rest _)
  "Re-pull bridge messages into the inbox buffer."
  (dsh-bridge-inbox))

;;; Verbs

;;;###autoload
(defun dsh-bridge-send (&optional session-id)
  "Send the region, or the whole buffer, to the DSH session as a prompt.
With a prefix argument, choose the target session for this call only, without
changing the pin.  A whole-buffer send asks for confirmation first, except in
`dsh-bridge-prompt-mode' where sending the whole buffer is the point."
  (interactive (list (dsh-bridge--read-session-override "Send to session: ")))
  (let ((whole (not (use-region-p))))
    (when (and whole
               (not (eq major-mode 'dsh-bridge-prompt-mode))
               (not (y-or-n-p (format "Send the whole %s buffer to DSH? "
                                      (buffer-name)))))
      (user-error "dsh-bridge: aborted"))
    (dsh-bridge-send-text (dsh-bridge--region-or-buffer) session-id)))

;;;###autoload
(defun dsh-bridge-draft (&optional session-id)
  "Send the region, or the whole buffer, to the DSH composer as a draft.
Like `dsh-bridge-send', but nothing is submitted; the text lands in the
composer for review.  With a prefix argument, choose the target session for
this call only."
  (interactive (list (dsh-bridge--read-session-override "Draft to session: ")))
  (dsh-bridge-send-draft (dsh-bridge--region-or-buffer) session-id))

;;;###autoload
(defun dsh-bridge-fetch (&optional session-id)
  "Fetch the latest DSH assistant reply into *dsh-bridge-output*.
With a prefix argument, fetch from a chosen session for this call only.
`g' or `f' in the output buffer re-fetches."
  (interactive (list (dsh-bridge--read-session-override "Fetch from session: ")))
  (dsh-bridge--call "GET"
                    (dsh-bridge--path "/output"
                                      (or session-id dsh-bridge-target-session))
                    nil
    (lambda (status body http-status)
      (let* ((alist (condition-case nil
                        (json-parse-string body :object-type 'alist)
                      (error nil)))
             (err (dsh-bridge--error-message status http-status alist)))
        (cond
         (err (message "dsh-bridge: %s" err))
         (t
          (with-current-buffer (get-buffer-create "*dsh-bridge-output*")
            (unless (eq major-mode 'dsh-bridge-view-mode)
              (dsh-bridge-view-mode))
            (setq-local revert-buffer-function #'dsh-bridge--revert-output)
            (setq-local dsh-bridge--view-content-session
                        (or (alist-get 'sessionId alist)
                            session-id dsh-bridge-target-session))
            (setq-local dsh-bridge--view-timestamp
                        (format-time-string "%H:%M:%S"))
            (setq header-line-format (dsh-bridge--view-header-line))
            (let ((inhibit-read-only t))
              (erase-buffer)
              (insert (or (cdr (assoc 'text alist)) ""))
              (goto-char (point-min))))
          (pop-to-buffer "*dsh-bridge-output*")
          (message "dsh-bridge: fetched reply from %s"
                   (or (dsh-bridge--label-from-response
                        alist (alist-get 'sessionId alist))
                       "last-active session"))))))))

;;;###autoload
(defun dsh-bridge-inbox ()
  "Pull DSH→Emacs messages into *dsh-bridge-inbox*, acking after success.
Entries are acked only after they are inserted, so a crash between the insert
and the ack redelivers them on the next pull (duplicates, not loss).
`g' or `i' in the inbox buffer re-pulls."
  (interactive)
  (let* ((result (dsh-bridge--request "GET" "/outbox" nil))
         (status (car result))
         (alist (cdr result)))
    (cond
     ((null status)
      (message "dsh-bridge: request failed (is `dsh web' running?)"))
     ((>= status 400)
      (message "dsh-bridge: %s"
               (or (alist-get 'error alist) (format "HTTP %s" status))))
     (t
      (let ((entries (alist-get 'entries alist))
            (overflowed (alist-get 'overflowed alist)))
        (when entries
          (with-current-buffer (get-buffer-create "*dsh-bridge-inbox*")
            (unless (eq major-mode 'dsh-bridge-view-mode)
              (dsh-bridge-view-mode))
            (setq-local revert-buffer-function #'dsh-bridge--revert-inbox)
            (setq-local dsh-bridge--view-timestamp
                        (format-time-string "%H:%M:%S"))
            (setq header-line-format (dsh-bridge--view-header-line))
            (let ((inhibit-read-only t))
              (dolist (entry entries)
                (insert (concat (dsh-bridge--inbox-header entry) "\n"))
                (insert (or (alist-get 'text entry) ""))
                (insert "\n\n"))
              (goto-char (point-min))))
          ;; Ack only after the insert above succeeded.
          (dsh-bridge--request "POST" "/outbox/ack"
                               `((ids . ,(mapcar (lambda (e) (alist-get 'id e)) entries)))))
        (message "dsh-bridge: pulled %d message%s%s"
                 (length entries)
                 (if (= (length entries) 1) "" "s")
                 (if overflowed " (overflow — some dropped)" ""))
        (when entries (pop-to-buffer "*dsh-bridge-inbox*")))))))

;;;###autoload
(defun dsh-bridge--prompt-buffer ()
  "Return the prompt buffer, ensuring it is in `dsh-bridge-prompt-mode'."
  (let ((buffer (get-buffer-create "*dsh-bridge-prompt*")))
    (with-current-buffer buffer
      (unless (eq major-mode 'dsh-bridge-prompt-mode)
        (dsh-bridge-prompt-mode)))
    buffer))

;;;###autoload
(defun dsh-bridge-prompt (&optional action)
  "Pop to the persistent prompt-editing buffer `*dsh-bridge-prompt*'.
ACTION, when non-nil, is a `display-buffer' action passed to `pop-to-buffer'.
The text survives sends, so a prompt can be edited and resubmitted; `C-c C-k'
erases the buffer."
  (interactive)
  (pop-to-buffer (dsh-bridge--prompt-buffer) action))

(defconst dsh-bridge-prompt-display-action
  '(display-buffer-reuse-window display-buffer-below-selected)
  "`display-buffer' action for opening the prompt buffer to reply.
Reuse the prompt's window when already visible, else show it below the
selected window, so the output buffer stays visible (cf. `flymake',
`debug').")

(defun dsh-bridge-reply ()
  "Pin the session whose output is shown, and open the prompt to reply.
In `*dsh-bridge-output*' the reply targets the session the shown reply came
from (pinning it); elsewhere it targets the current target.  The prompt is
shown in another window so the output stays visible."
  (interactive)
  (let ((session-id (and (eq major-mode 'dsh-bridge-view-mode)
                         dsh-bridge--view-content-session)))
    (when (and session-id (dsh-bridge--session-live-p session-id))
      (dsh-bridge-select-session session-id)))
  (pop-to-buffer (dsh-bridge--prompt-buffer)
                 dsh-bridge-prompt-display-action))

;;; The prompt buffer

(defun dsh-bridge--prompt-mode-setup ()
  "Common setup for `dsh-bridge-prompt-mode'."
  (setq-local header-line-format (dsh-bridge--prompt-header-line)))

(declare-function markdown-mode "markdown-mode")
(declare-function dsh-bridge-prompt-mode "dsh-bridge")

(defmacro dsh-bridge--define-prompt-mode (parent)
  "Define `dsh-bridge-prompt-mode' as a variant of PARENT.
PARENT is `markdown-mode' or `text-mode', chosen at load time: the mode is
defined once, with a literal symbol parent.  A conditional expression cannot
go directly in the parent slot of `define-derived-mode' — the macro quotes it
into the mode metadata and the docstring generation calls `symbol-name' on it
— so the choice is resolved here, driven by `dsh-bridge-prompt-markdown' and
`(require \\='markdown-mode nil t)'."
  `(define-derived-mode dsh-bridge-prompt-mode ,parent "DSH-Prompt"
     "Major mode for composing DSH prompts.
`C-c C-c' sends the region or whole buffer (the buffer is not cleared, so
text survives for edit-and-resubmit), `C-c C-d' pushes it as a composer
draft, `C-c C-k' erases the buffer."
     (dsh-bridge--prompt-mode-setup)))

;; The map is created by whichever branch of the `if' runs; declare it here so
;; the byte-compiler knows the `define-key' forms below are valid.
(defvar dsh-bridge-prompt-mode-map)

(if (and dsh-bridge-prompt-markdown (require 'markdown-mode nil t))
    (dsh-bridge--define-prompt-mode markdown-mode)
  (dsh-bridge--define-prompt-mode text-mode))

(define-key dsh-bridge-prompt-mode-map (kbd "C-c C-c") #'dsh-bridge-send)
(define-key dsh-bridge-prompt-mode-map (kbd "C-c C-d") #'dsh-bridge-draft)
(define-key dsh-bridge-prompt-mode-map (kbd "C-c C-k") #'dsh-bridge-erase-prompt)

(defun dsh-bridge-erase-prompt ()
  "Erase the contents of the prompt buffer."
  (interactive)
  (erase-buffer))

(easy-menu-define dsh-bridge-prompt-menu dsh-bridge-prompt-mode-map
  "Menu bar menu for the `*dsh-bridge-prompt*' buffer."
  '("DSH Bridge"
    ["Send" dsh-bridge-send
     :help "Send the region (or whole buffer) to DSH as a prompt"]
    ["Send as Draft" dsh-bridge-draft
     :help "Send the region (or whole buffer) to the DSH composer as a draft"]
    ["Erase Prompt" dsh-bridge-erase-prompt
     :help "Clear the prompt buffer"]
    "---"
    ["Select Session…" dsh-bridge-select-session
     :help "Pin the target session"]
    ["List Sessions" dsh-bridge-list-sessions
     :help "Browse DSH sessions"]))

;;; Session targeting

(defun dsh-bridge-current-session ()
  "Message the DSH session the bridge currently targets."
  (interactive)
  (let* ((result (dsh-bridge--request "GET" "/current" nil))
         (status (car result))
         (alist (cdr result))
         (session-id (and alist (alist-get 'sessionId alist))))
    (cond
     ((null status)
      (message "dsh-bridge: request failed (is `dsh web' running?)"))
     ((>= status 400)
      (message "dsh-bridge: %s"
               (or (and alist (alist-get 'error alist))
                   (format "HTTP %s" status))))
     (session-id
      (setq dsh-bridge-target-session session-id)
      (message "dsh-bridge: targeting session %s"
               (or (dsh-bridge--label-for-id session-id) session-id)))
     (t
      (setq dsh-bridge-target-session nil)
      (message "dsh-bridge: targeting the last-active session")))))

(make-obsolete 'dsh-bridge-current-session
               "the `dsh-bridge' dispatcher header shows the current target"
               "0.1.0")

(defun dsh-bridge--refresh-view-headers ()
  "Refresh header lines of live bridge buffers after a retarget."
  (dolist (name '("*dsh-bridge-output*" "*dsh-bridge-inbox*"))
    (when (buffer-live-p (get-buffer name))
      (with-current-buffer (get-buffer name)
        (when (eq major-mode 'dsh-bridge-view-mode)
          (setq header-line-format (dsh-bridge--view-header-line))))))
  (when (buffer-live-p (get-buffer "*dsh-bridge-prompt*"))
    (with-current-buffer "*dsh-bridge-prompt*"
      (when (eq major-mode 'dsh-bridge-prompt-mode)
        (setq header-line-format (dsh-bridge--prompt-header-line))))))

;;;###autoload
(defun dsh-bridge-select-session (session-id)
  "Set the DSH session the bridge targets to SESSION-ID.
SESSION-ID is a session id string, or nil to target the last-active session."
  (interactive
   (list
    (let* ((choices (dsh-bridge--live-session-choices))
           (choice (completing-read "Target session: "
                                    (append choices '(("(last-active)" . nil)))
                                    nil t)))
      (if (string= choice "(last-active)") nil
        (cdr (assoc choice choices))))))
  (let* ((result (dsh-bridge--request "POST" "/select"
                  (if session-id
                      `((sessionId . ,session-id))
                    ;; `json-encode' only emits JSON null for the Lisp value
                    ;; nil here (json-null is nil in this Emacs); sending the
                    ;; :json-null keyword would encode as the *string* "json-null".
                    '((sessionId . nil)))))
         (status (car result))
         (alist (cdr result)))
    (cond
     ((null status)
      (message "dsh-bridge: request failed (is `dsh web' running?)"))
     ((>= status 400)
      (message "dsh-bridge: %s"
               (or (alist-get 'error alist) (format "HTTP %s" status))))
     ((and alist (assoc 'error alist))
      (message "dsh-bridge: %s" (alist-get 'error alist)))
     (t
      (setq dsh-bridge-target-session session-id)
      (dsh-bridge--refresh-view-headers)
      (dsh-bridge--refresh-sessions-buffer)
      (message "dsh-bridge: targeting %s"
               (or (and session-id
                        (or (dsh-bridge--label-for-id session-id) session-id))
                   "last-active session"))))))

;;; The sessions buffer

(defface dsh-bridge-current-target-face
  '((t :inherit bold :foreground "ForestGreen"))
  "Face for the current target session in `*dsh-bridge-sessions*'."
  :group 'dsh-bridge)

(defface dsh-bridge-saved-session-face
  '((t :inherit shadow))
  "Face for saved (cold) sessions in `*dsh-bridge-sessions*'."
  :group 'dsh-bridge)

(defface dsh-bridge-untitled-face
  '((t :inherit shadow :slant italic))
  "Face for the \"Untitled session\" placeholder in `*dsh-bridge-sessions*'."
  :group 'dsh-bridge)

(defun dsh-bridge--target-marker (session)
  "Return the leftmost marker cell for SESSION: \"*\" when it is the pinned
target, else a space."
  (if (equal (alist-get 'id session) dsh-bridge-target-session)
      (propertize "*" 'face 'dsh-bridge-current-target-face)
    " "))

(defun dsh-bridge--running-marker (session)
  "Return the running-marker cell for SESSION: \"…\" when running, else a space."
  (if (alist-get 'running session) "…" " "))

(defun dsh-bridge--session-cell (session)
  "Session name cell for SESSION, with saved/untitled faces."
  (let* ((title (alist-get 'title session))
         (untitled (not (and (stringp title) (not (string-empty-p title)))))
         (label (if untitled "Untitled session" title))
         (face (cond ((not (alist-get 'live session)) 'dsh-bridge-saved-session-face)
                     (untitled 'dsh-bridge-untitled-face)
                     (t nil))))
    (if face (propertize label 'face face) label)))

(defun dsh-bridge--age-sorter (a b)
  "Sort predicate for the Age column: ascending by activity timestamp.
A and B are `tabulated-list' entries (ID COLS); the Age cell is a string
carrying the raw ms-epoch timestamp in its `dsh-bridge-age-ts' text property."
  (let* ((n (seq-position tabulated-list-format "Age"
                           (lambda (e elt) (equal (car e) elt))))
         (ta (get-text-property 0 'dsh-bridge-age-ts (aref (cadr a) n)))
         (tb (get-text-property 0 'dsh-bridge-age-ts (aref (cadr b) n))))
    (< ta tb)))

(defun dsh-bridge--session-entry (session)
  "Return a `tabulated-list' entry (ID . COLS) for SESSION (a row alist)."
  (let* ((id (alist-get 'id session))
         (activity (dsh-bridge--session-activity session))
         (age (propertize (dsh-bridge--relative-age activity)
                          'dsh-bridge-age-ts activity))
         (workspace (dsh-bridge--workspace-label session))
         (cwd (alist-get 'cwd session))
         (workspace-cell (if (and (stringp cwd) (not (string-empty-p cwd)))
                             (propertize workspace 'help-echo cwd)
                           workspace))
         (cols (vector (dsh-bridge--target-marker session)
                       (dsh-bridge--running-marker session)
                       (dsh-bridge--session-cell session)
                       age
                       workspace-cell)))
    (when dsh-bridge-show-session-ids
      (setq cols (vconcat cols (vector id))))
    (list id cols)))

(define-derived-mode dsh-bridge-sessions-mode tabulated-list-mode "DSH-Sessions"
  "Major mode for browsing DSH sessions.
`RET' pins the session under point (live only), `u' unpins, `p' pins and pops
to the prompt buffer, `f' peeks the session's latest reply without changing
the pin, `v' toggles saved sessions, `w' copies the session id under point,
`D' describes the session, `g' re-fetches the list, `S' sorts by column."
  (setq-local dsh-bridge--show-saved dsh-bridge-sessions-show-saved))

(define-key dsh-bridge-sessions-mode-map (kbd "RET")
            #'dsh-bridge-select-session-at-point)
(define-key dsh-bridge-sessions-mode-map (kbd "u")
            #'dsh-bridge-unpin-session)
(define-key dsh-bridge-sessions-mode-map (kbd "p")
            #'dsh-bridge-select-session-at-point-and-prompt)
(define-key dsh-bridge-sessions-mode-map (kbd "f")
            #'dsh-bridge-peek-session)
(define-key dsh-bridge-sessions-mode-map (kbd "v")
            #'dsh-bridge-toggle-saved-sessions)
(define-key dsh-bridge-sessions-mode-map (kbd "w")
            #'dsh-bridge-copy-session-id)
(define-key dsh-bridge-sessions-mode-map (kbd "D")
            #'dsh-bridge-describe-session)

(easy-menu-define dsh-bridge-sessions-menu dsh-bridge-sessions-mode-map
  "Menu bar menu for the `*dsh-bridge-sessions*' buffer."
  '("DSH Bridge"
    ["Pin Session" dsh-bridge-select-session-at-point
     :help "Pin the session under point"]
    ["Pin & Edit Prompt" dsh-bridge-select-session-at-point-and-prompt
     :help "Pin the session under point and open the prompt buffer"]
    ["Unpin" dsh-bridge-unpin-session
     :help "Unpin the target (use last-active)"]
    ["Peek Reply" dsh-bridge-peek-session
     :help "Fetch the session's latest reply without pinning"]
    ["Toggle Saved Sessions" dsh-bridge-toggle-saved-sessions
     :help "Show or hide saved (cold) sessions"]
    ["Copy Session Id" dsh-bridge-copy-session-id
     :help "Copy the session id under point"]
    ["Describe Session" dsh-bridge-describe-session
     :help "Show the session's details, including its id"]
    "---"
    ["Refresh" revert-buffer
     :help "Re-fetch the session list"]
    "---"
    ["Select Session…" dsh-bridge-select-session
     :help "Pin a session"]
    ["DSH Bridge Dispatcher…" dsh-bridge
     :help "Open the dispatcher"]))

(defun dsh-bridge-select-session-at-point ()
  "Select the DSH session shown on the current line of the session list."
  (interactive)
  (let ((id (tabulated-list-get-id)))
    (when id
      (if (dsh-bridge--session-live-p id)
          (dsh-bridge-select-session id)
        (message "dsh-bridge: session %s is not live"
                 (or (dsh-bridge--label-for-id id) id))))))

(defun dsh-bridge-unpin-session ()
  "Unpin the target session (the bridge targets the last-active session)."
  (interactive)
  (dsh-bridge-select-session nil))

(defun dsh-bridge-select-session-at-point-and-prompt ()
  "Pin the session under point and pop to `*dsh-bridge-prompt*'."
  (interactive)
  (let ((id (tabulated-list-get-id)))
    (if (and id (dsh-bridge--session-live-p id))
        (progn
          (dsh-bridge-select-session id)
          (dsh-bridge-prompt))
      (message "dsh-bridge: session %s is not live"
               (or (dsh-bridge--label-for-id id) id)))))

(defun dsh-bridge-peek-session ()
  "Fetch the session under point's latest reply into *dsh-bridge-output*.
The pin is not changed: this is a one-shot fetch, like `C-u
dsh-bridge-fetch'."
  (interactive)
  (let ((id (tabulated-list-get-id)))
    (if id
        (dsh-bridge-fetch id)
      (message "dsh-bridge: no session under point"))))

(defun dsh-bridge-toggle-saved-sessions ()
  "Toggle showing saved (cold) sessions in `*dsh-bridge-sessions*'."
  (interactive)
  (setq dsh-bridge--show-saved (not dsh-bridge--show-saved))
  (dsh-bridge--list-sessions-in-buffer)
  (message "dsh-bridge: %s saved sessions"
           (if dsh-bridge--show-saved "showing" "hiding")))

(defun dsh-bridge-copy-session-id ()
  "Copy the raw DSH session id under point to the kill ring."
  (interactive)
  (let ((id (tabulated-list-get-id)))
    (if id
        (progn
          (kill-new id)
          (message "dsh-bridge: copied session id %s" id))
      (message "dsh-bridge: no session under point"))))

(defun dsh-bridge-describe-session ()
  "Show details of the session under point, including its raw id."
  (interactive)
  (let ((id (tabulated-list-get-id)))
    (if (not id)
        (message "dsh-bridge: no session under point")
      (let* ((session (dsh-bridge--session-for-id id))
             (buffer (get-buffer-create "*dsh-bridge-session-details*")))
        (with-current-buffer buffer
          (let ((inhibit-read-only t))
            (erase-buffer)
            (insert (format "Session id:   %s\n" id))
            (when session
              (insert (format "Label:        %s\n"
                              (dsh-bridge--session-label session)))
              (insert (format "State:        %s\n"
                              (if (alist-get 'live session) "live" "saved")))
              (insert (format "Directory:    %s\n"
                              (or (alist-get 'cwd session) "")))
              (let ((ts (or (alist-get 'lastActive session)
                            (alist-get 'createdAt session))))
                (insert (format "Last active:  %s\n"
                                (if ts (format-time-string "%Y-%m-%d %H:%M:%S"
                                                           (/ ts 1000))
                                  "")))))
            (goto-char (point-min))))
        (with-current-buffer buffer
          (special-mode))
        (pop-to-buffer buffer)))))

(defun dsh-bridge--list-sessions-in-buffer ()
  "Fill `*dsh-bridge-sessions*' with the current session list.
Returns non-nil when sessions were listed."
  (let ((sessions (dsh-bridge--fetch-sessions)))
    (if (null sessions)
        nil
      (with-current-buffer (get-buffer-create "*dsh-bridge-sessions*")
        (unless (eq major-mode 'dsh-bridge-sessions-mode)
          (dsh-bridge-sessions-mode))
        ;; Override tabulated-list's re-print-only revert: `g' must re-fetch
        ;; the session list from the host.
        (setq-local revert-buffer-function
                    (lambda (&rest _) (dsh-bridge--list-sessions-in-buffer)))
        (setq tabulated-list-format
              (let ((format [("*" 1 t)
                             ("R" 1 t)
                             ("Session" 40 t)
                             ("Age" 8 dsh-bridge--age-sorter)
                             ("Workspace" 0 t)]))
                (if dsh-bridge-show-session-ids
                    (vconcat format [("Id" 40 t)])
                  format)))
        (setq tabulated-list-sort-key '("Age" . t))
        (setq tabulated-list-entries
              (mapcar #'dsh-bridge--session-entry
                      (if dsh-bridge--show-saved
                          sessions
                        (seq-filter (lambda (s) (alist-get 'live s)) sessions))))
        (tabulated-list-init-header)
        (tabulated-list-print))
      t)))

(defun dsh-bridge--refresh-sessions-buffer ()
  "Re-render `*dsh-bridge-sessions*' in place if it is live."
  (when (buffer-live-p (get-buffer "*dsh-bridge-sessions*"))
    (with-current-buffer "*dsh-bridge-sessions*"
      (when (eq major-mode 'dsh-bridge-sessions-mode)
        (dsh-bridge--list-sessions-in-buffer)))))

;;;###autoload
(defun dsh-bridge-list-sessions ()
  "List DSH sessions in a tabulated buffer.
In the session list: `RET' pins the session under point (live only), `u'
unpins, `p' pins and pops to the prompt buffer, `f' peeks the session's
latest reply without changing the pin, `v' toggles saved sessions, `w' copies
the session id, `D' shows session details, `g' re-fetches, `S' sorts by
column."
  (interactive)
  (if (dsh-bridge--list-sessions-in-buffer)
      (pop-to-buffer "*dsh-bridge-sessions*")
    (message "dsh-bridge: no sessions (or request failed)")))

;;; The dispatcher

;;;###autoload
(transient-define-prefix dsh-bridge ()
  "Dispatch DSH bridge actions.
The header shows the current target session; the verbs act on it.  `s' sends
the region or buffer as a prompt, `d' sends it as a draft, `p' opens the
prompt buffer, `f' fetches the latest reply, `i' pulls the inbox, `S' selects
the target session, `l' lists sessions."
  dsh-bridge--dispatcher-layout)

;;; Menu bar (under Tools)

(defvar dsh-bridge-menu
  (easy-menu-create-menu
   "DSH Bridge"
   '(["DSH Bridge Dispatcher…" dsh-bridge
      :help "Open the DSH bridge dispatcher"]
     "---"
     ["Edit Prompt Buffer" dsh-bridge-prompt
      :help "Pop to the persistent prompt buffer"]
     ["Send Region or Buffer" dsh-bridge-send
      :help "Send the region (or whole buffer) to DSH as a prompt"]
     ["Send as Draft" dsh-bridge-draft
      :help "Send the region (or whole buffer) to the DSH composer as a draft"]
     ["Fetch Latest Reply" dsh-bridge-fetch
      :help "Fetch the latest assistant reply into *dsh-bridge-output*"]
     ["Pull Inbox" dsh-bridge-inbox
      :help "Pull Send-to-Emacs messages into *dsh-bridge-inbox*"]
     "---"
     ["Select Session…" dsh-bridge-select-session
      :help "Pin the target session (or choose last-active to unpin)"]
     ["List Sessions" dsh-bridge-list-sessions
      :help "Browse DSH sessions in a tabulated list"]))
  "DSH Bridge menu, installed under Tools.")

(easy-menu-add-item nil '("Tools") dsh-bridge-menu)

;;; Back-compat: the pre-interface command names, obsolete for one cycle.

(define-obsolete-function-alias 'dsh-bridge-send-region 'dsh-bridge-send "0.1.0")
(define-obsolete-function-alias 'dsh-bridge-send-buffer 'dsh-bridge-send "0.1.0")
(define-obsolete-function-alias 'dsh-bridge-get-output 'dsh-bridge-fetch "0.1.0")
(define-obsolete-function-alias 'dsh-bridge-pull-inbox 'dsh-bridge-inbox "0.1.0")
(define-obsolete-function-alias 'dsh-bridge-send-draft-region 'dsh-bridge-draft "0.1.0")
(define-obsolete-function-alias 'dsh-bridge-send-draft-buffer 'dsh-bridge-draft "0.1.0")

(provide 'dsh-bridge)
;;; dsh-bridge.el ends here
