;;; dsh-bridge.el --- Emacs <-> DeepSeek Harness bridge -*- lexical-binding: t; -*-

;; Copyright (C) 2026  Chong Yidong <cyd@stupidchicken.com>
;;
;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;; Author: Chong Yidong <cyd@stupidchicken.com>
;; Version: 0.1.0
;; Package-Requires: ((emacs "29.1"))
;; Keywords: tools, convenience

;;; Commentary:

;; Two-way bridge between Emacs and a running DeepSeek Harness session.  Talks
;; to the `dsh-emacs-bridge' DSH plugin over loopback HTTP.
;;
;; Interface (see emacs-interface-plan.md):
;;   dsh-bridge                     transient dispatcher; header shows the target
;;   dsh-bridge-send / -draft       region-or-buffer -> prompt / composer draft
;;   dsh-bridge-fetch               latest reply -> *dsh-bridge-output*
;;   dsh-bridge-inbox               pull "Send to Emacs" messages -> *dsh-bridge-inbox*
;;   dsh-bridge-prompt              persistent prompt-editing buffer
;;   dsh-bridge-select-session      pin the target session
;;   dsh-bridge-list-sessions       tabulated session browser
;;
;; The bridge targets the last-active session unless one is pinned with
;; `dsh-bridge-select-session'; a prefix argument to send/draft/fetch makes a
;; one-shot session choice for that call only.
;;
;; No global keybinding by default: `C-c <letter>' is reserved for users.  The
;; README documents `(keymap-global-set "C-c d" #'dsh-bridge)'; the Tools >
;; DSH Bridge menu provides key-free access, and the view buffers bind the
;; dispatcher's letters buffer-locally.

;;; Code:

(require 'url)
(require 'url-util)
(require 'subr-x)
(require 'seq)
(require 'json)
(require 'transient)

(defgroup dsh-bridge nil
  "Emacs <-> DeepSeek Harness bridge."
  :group 'tools)

(defcustom dsh-bridge-url "http://127.0.0.1:3080/dsh-bridge"
  "Base URL of the `dsh-emacs-bridge' HTTP route."
  :type 'string
  :group 'dsh-bridge)

(defcustom dsh-bridge-token-file
  (expand-file-name "dsh-bridge-token"
                    (let ((home (string-trim (or (getenv "DSH_HOME") ""))))
                      (if (string-empty-p home) "~/.dsh" home)))
  "File holding the shared bridge token, generated by the DSH plugin.
The plugin stores it at `$DSH_HOME/dsh-bridge-token' (default
`~/.dsh/dsh-bridge-token').  A relative `$DSH_HOME' resolves against
the `dsh' process's working directory, so set this option explicitly
when using one."
  :type 'file
  :group 'dsh-bridge)

(defcustom dsh-bridge-token nil
  "Bearer token for the bridge, or nil to read `dsh-bridge-token-file'.
When non-nil, this value is sent as `Authorization: Bearer <token>' on every
request."
  :type '(choice (const :tag "Read from file" nil) string)
  :group 'dsh-bridge)

(defcustom dsh-bridge-timeout 5
  "Timeout in seconds for synchronous bridge requests."
  :type 'number
  :group 'dsh-bridge)

(defcustom dsh-bridge-prompt-markdown t
  "Use `markdown-mode' as the parent of `dsh-bridge-prompt-mode' when available.
markdown-mode is not part of Emacs core.  When it is not installed, or this
option is nil, the prompt buffer derives from `text-mode'.  The choice is
resolved when this package is loaded; changing the option takes effect after
reloading."
  :type 'boolean
  :group 'dsh-bridge)

(defcustom dsh-bridge-show-session-ids nil
  "When non-nil, show raw DSH session ids in the sessions list.
Session ids are internal to the bridge; by default the list and the selector
show only friendly labels.  Enable this for debugging."
  :type 'boolean
  :group 'dsh-bridge)

(defvar dsh-bridge-target-session nil
  "DSH session id the bridge targets, or nil for the last-active session.
Set with `dsh-bridge-select-session'.")

(defvar dsh-bridge--sessions-cache nil
  "Last list of session row alists fetched from the host, or nil.
Kept so an id can be turned back into its display label without an extra HTTP
request.")

;;; Low-level HTTP plumbing

(defun dsh-bridge--response-body (buffer)
  "Return the HTTP response body (text after the headers) of BUFFER.
The url-http response buffer is unibyte, so decode the body as UTF-8."
  (with-current-buffer buffer
    (goto-char (point-min))
    (if (re-search-forward "\r?\n\r?\n" nil t)
        (decode-coding-string
         (buffer-substring-no-properties (point) (point-max)) 'utf-8)
      "")))

(defun dsh-bridge--token ()
  "Return the bridge bearer token as a unibyte string, or nil if none.

`insert-file-contents' yields a multibyte string, and a multibyte (even
pure-ASCII) Authorization header value poisons url-http's request
concatenation: when the request body then contains non-ASCII bytes, the
request string becomes multibyte and url-http errors with \"Multibyte
text in HTTP request\" (bug#23750) in the process sentinel — surfacing
only as a request timeout.  The token is hex, so coercing to unibyte is
lossless."
  (let ((token (or dsh-bridge-token
                   (and (file-readable-p dsh-bridge-token-file)
                        (with-temp-buffer
                          (insert-file-contents dsh-bridge-token-file)
                          (string-trim (buffer-string)))))))
    (and token (string-to-unibyte token))))

(defun dsh-bridge--extra-headers (payload)
  "Return the HTTP header alist for a request with PAYLOAD (nil for no body).
Always includes the bearer Authorization header when a token is known."
  (let ((token (dsh-bridge--token)))
    (append (and payload '(("Content-Type" . "application/json")))
            (and token (list (cons "Authorization" (concat "Bearer " token)))))))

(defun dsh-bridge--path (path session-id)
  "Return PATH with an optional ?sessionId= query parameter."
  (if session-id
      (format "%s?sessionId=%s" path (url-hexify-string session-id))
    path))

(defun dsh-bridge--error-message (status http-status alist)
  "Return a user-facing error message for a failed request, or nil on success.
STATUS is the url-retrieve status plist, HTTP-STATUS the HTTP status code (or
nil), and ALIST the decoded JSON body (or nil)."
  (let ((transport-error (plist-get status :error)))
    (cond
     (transport-error (format "request failed: %s" transport-error))
     ((and http-status (>= http-status 400))
      (format "HTTP %s: %s" http-status
              (or (alist-get 'error alist) "error")))
     ((and alist (assoc 'error alist)) (alist-get 'error alist))
     (t nil))))

(defun dsh-bridge--call (method path payload callback)
  "Perform METHOD request to PATH under `dsh-bridge-url'.
PAYLOAD is an alist encoded as JSON (for POST) or nil (for GET).
CALLBACK is invoked with (status body-string HTTP-STATUS), where STATUS is nil
on a completed request (whatever the HTTP status) or an `:error' plist on a
transport failure/timeout.  Uses `url-retrieve-synchronously': a request here
is a short loopback round-trip, and the async `url-retrieve' path reports
process-sentinel failures (such as the bug#23750 \"Multibyte text in HTTP
request\" error) only via `message', which made them hard to diagnose."
  (let ((url-request-method method)
        (url-request-data
         (and payload (encode-coding-string (json-encode payload) 'utf-8)))
        (url-request-extra-headers (dsh-bridge--extra-headers payload)))
    (let ((buf nil)
          (err nil))
      (condition-case e
          (setq buf (url-retrieve-synchronously (concat dsh-bridge-url path)
                                                t nil dsh-bridge-timeout))
        (error (setq err e)))
      (cond
       (err (funcall callback (list :error (error-message-string err)) nil nil))
       ((null buf) (funcall callback '(:error "request timed out") nil nil))
       (t
        (let ((http-status (with-current-buffer buf
                             (and (boundp 'url-http-response-status)
                                  url-http-response-status)))
              (body (dsh-bridge--response-body buf)))
          (kill-buffer buf)
          (funcall callback nil body http-status)))))))

(defun dsh-bridge--request (method path payload)
  "Perform METHOD request to PATH and return (STATUS . ALIST).
STATUS is the HTTP status code, or nil on transport failure.  ALIST is the
decoded JSON object (JSON null/false become nil, arrays become lists), or nil
when the body is not a JSON object."
  (let ((url-request-method method)
        (url-request-data
         (and payload (encode-coding-string (json-encode payload) 'utf-8)))
        (url-request-extra-headers (dsh-bridge--extra-headers payload)))
    (let ((buf (url-retrieve-synchronously (concat dsh-bridge-url path)
                                           t nil dsh-bridge-timeout)))
      (if (null buf)
          (cons nil nil)
        (with-current-buffer buf
          (let* ((status (and (boundp 'url-http-response-status)
                              url-http-response-status))
                 (body (dsh-bridge--response-body buf))
                 (alist (condition-case nil
                            (json-parse-string body :object-type 'alist
                                               :array-type 'list
                                               :null-object nil
                                               :false-object nil)
                          (error nil))))
            (kill-buffer buf)
            (cons status alist)))))))

(defun dsh-bridge--fetch-sessions ()
  "Return the DSH session list as a list of alists, or nil on error.
Also caches the list in `dsh-bridge--sessions-cache' for id->label lookups."
  (let* ((result (dsh-bridge--request "GET" "/sessions" nil))
         (alist (cdr result))
         (sessions (and alist (assoc 'sessions alist)
                        (cdr (assoc 'sessions alist)))))
    (when sessions
      (setq dsh-bridge--sessions-cache sessions))
    sessions))

(defun dsh-bridge--inbox-header (entry)
  "Return a provenance header line for an outbox ENTRY."
  (format "--- %s%s%s ---"
          (or (alist-get 'source entry) "bridge")
          (let ((sid (alist-get 'sessionId entry)))
            (if sid
                (format " | session %s"
                        (or (dsh-bridge--label-for-id sid) sid))
              ""))
          (let ((ts (alist-get 'ts entry)))
            (if ts (format " | %s"
                           (format-time-string "%Y-%m-%d %H:%M:%S"
                                               (/ ts 1000)))
              ""))))

;;; Session labels

(defun dsh-bridge--session-label (session)
  "Return the display label for SESSION (a row alist).
Mirrors DSH's display title: the session title, else the workspace basename,
else the raw id."
  (or (let ((title (alist-get 'title session)))
        (and (stringp title) (not (string-empty-p title)) title))
      (let ((cwd (alist-get 'cwd session)))
        (and (stringp cwd) (not (string-empty-p cwd))
             (let ((base (file-name-nondirectory (directory-file-name cwd))))
               (and (not (string-empty-p base)) base))))
      (alist-get 'id session)))

(defun dsh-bridge--session-for-id (id)
  "Return the cached session row alist whose id is ID, or nil."
  (seq-find (lambda (s) (equal (alist-get 'id s) id))
            dsh-bridge--sessions-cache))

(defun dsh-bridge--label-for-id (id)
  "Return the display label for session ID, or nil when unknown."
  (let ((session (dsh-bridge--session-for-id id)))
    (and session (dsh-bridge--session-label session))))

(defun dsh-bridge--label-from-response (alist fallback-id)
  "Return a display label from a bridge response ALIST.
Prefers the response's `title' (fresh from the host), then the cached label
of FALLBACK-ID, then FALLBACK-ID itself."
  (or (alist-get 'title alist)
      (and fallback-id
           (or (dsh-bridge--label-for-id fallback-id) fallback-id))))

(defun dsh-bridge--session-activity (session)
  "Return the ms-epoch activity timestamp for SESSION (a row alist).
Live sessions use their last event time; saved sessions their creation time."
  (or (alist-get 'lastActive session) (alist-get 'createdAt session) 0))

(defun dsh-bridge--relative-age (ts &optional now)
  "Return a short age string for ms-epoch timestamp TS.
NOW is the reference time in seconds (default: the current time)."
  (let* ((now (or now (float-time)))
         (secs (max 0 (- now (/ ts 1000.0)))))
    (cond
     ((< secs 60) "now")
     ((< secs 3600) (format "%dm" (floor (/ secs 60))))
     ((< secs 86400) (format "%dh" (floor (/ secs 3600))))
     ((< secs (* 7 86400)) (format "%dd" (floor (/ secs 86400))))
     (t (format-time-string "%Y-%m-%d" (/ ts 1000))))))

;;; Target helpers

(defun dsh-bridge--target-label ()
  "Label of the current target: the pinned session's label, or \"last-active\"."
  (if dsh-bridge-target-session
      (or (dsh-bridge--label-for-id dsh-bridge-target-session)
          dsh-bridge-target-session)
    "last-active"))

(defun dsh-bridge--target-header ()
  "Header string for the dispatcher: the bridge name plus the target."
  (format "DSH Bridge · target: %s" (dsh-bridge--target-label)))

(defun dsh-bridge--live-session-choices ()
  "Return an alist of (LABEL . ID) for live sessions, or nil."
  (mapcar (lambda (s) (cons (dsh-bridge--session-label s) (alist-get 'id s)))
          (seq-filter (lambda (s) (alist-get 'live s))
                      (dsh-bridge--fetch-sessions))))

(defun dsh-bridge--read-session-override (prompt)
  "With a prefix argument, read a live session for one-shot use.
Returns the chosen session id, or nil without a prefix argument (the caller
then uses the pinned/last-active target)."
  (when current-prefix-arg
    (let ((choices (dsh-bridge--live-session-choices)))
      (if (null choices)
          (user-error "dsh-bridge: no live sessions")
        (cdr (assoc (completing-read prompt choices nil t) choices))))))

(defun dsh-bridge--region-or-buffer ()
  "Return the region text if the region is active, else the whole buffer."
  (if (use-region-p)
      (buffer-substring-no-properties (region-beginning) (region-end))
    (buffer-substring-no-properties (point-min) (point-max))))

;;; Text senders (internal)

(defun dsh-bridge-send-text (text &optional session-id)
  "Send TEXT to the DSH session as a prompt.
SESSION-ID overrides the pinned target for this call only."
  (let* ((target (or session-id dsh-bridge-target-session))
         (payload (append (list (cons 'text text))
                          (and target (list (cons 'sessionId target))))))
    (dsh-bridge--call "POST" "/send" payload
      (lambda (status body http-status)
        (let* ((alist (condition-case nil
                          (json-parse-string body :object-type 'alist)
                        (error nil)))
               (err (dsh-bridge--error-message status http-status alist)))
          (cond
           (err (message "dsh-bridge: %s" err))
           ((null alist)
            (message "dsh-bridge: unreadable response: %s" body))
           (t (message "dsh-bridge: sent to %s"
                       (or (dsh-bridge--label-from-response alist target)
                           "the last-active session")))))))))

(defun dsh-bridge-send-draft (text &optional session-id)
  "Send TEXT to the DSH composer as a draft (not submitted).
SESSION-ID overrides the pinned target for this call only."
  (let* ((target (or session-id dsh-bridge-target-session))
         (payload (append (list (cons 'text text))
                          (and target (list (cons 'sessionId target))))))
    (dsh-bridge--call "POST" "/draft" payload
      (lambda (status body http-status)
        (let* ((alist (condition-case nil
                          (json-parse-string body :object-type 'alist)
                        (error nil)))
               (err (dsh-bridge--error-message status http-status alist)))
          (cond
           (err (message "dsh-bridge: %s" err))
           ((null alist)
            (message "dsh-bridge: unreadable response: %s" body))
           (t (message "dsh-bridge: draft pushed to %s"
                       (or (dsh-bridge--label-from-response alist target)
                           "the active session")))))))))

;;; Shared letter->command table (dispatcher + view buffers)

;; The verb suffixes are the single source of truth for the letter keys: the
;; view buffers' keymap and the dispatcher layout are both derived from it, so
;; they cannot drift apart.  `eval-and-compile' because the transient macro
;; expansion reads the value at compile time.
(eval-and-compile
  (defconst dsh-bridge--verb-suffixes
    '(("s" dsh-bridge-send :description "send region/buffer (prompt)")
      ("d" dsh-bridge-draft :description "send region/buffer (draft)")
      ("f" dsh-bridge-fetch :description "fetch latest reply")
      ("i" dsh-bridge-inbox :description "pull \"Send to Emacs\" messages")
      ("S" dsh-bridge-select-session :description "select session")
      ("l" dsh-bridge-list-sessions :description "list sessions"))
    "Suffix specs shared by the `dsh-bridge' dispatcher and the view buffers.
Each spec is (KEY COMMAND DESCRIPTION).")

  (defconst dsh-bridge--dispatcher-layout
    (vconcat (list :description '(lambda () (dsh-bridge--target-header)))
             dsh-bridge--verb-suffixes
             (list '("p" dsh-bridge-prompt :description "edit prompt buffer")
                   '("q" transient-quit-one :description "quit")))
    "Layout of the `dsh-bridge' dispatcher.
The verb suffixes come from `dsh-bridge--verb-suffixes'; `p' (prompt buffer)
and `q' (quit) are dispatcher-only."))

;;; View buffers (*dsh-bridge-output*, *dsh-bridge-inbox*)

(defvar-local dsh-bridge--view-timestamp nil
  "Time the current view buffer was last refreshed, or nil.")

(defvar-local dsh-bridge--view-content-session nil
  "Session the current view buffer's content came from, or nil.
Set only in `*dsh-bridge-output*': a peek or `C-u' override fills the buffer
with a reply that is not the pinned target's, and the header line must say
so.  The inbox (a global log) leaves this nil and labels the target.")

(defun dsh-bridge--view-header-line ()
  "Header line for the output/inbox buffers: provenance plus refresh time."
  (format "DSH Bridge · %s%s"
          (if dsh-bridge--view-content-session
              (format "reply from: %s"
                      (or (dsh-bridge--label-for-id
                           dsh-bridge--view-content-session)
                          dsh-bridge--view-content-session))
            (format "target: %s" (dsh-bridge--target-label)))
          (if dsh-bridge--view-timestamp
              (format " · refreshed %s" dsh-bridge--view-timestamp)
            "")))

(defun dsh-bridge--prompt-header-line ()
  "Header line for the prompt buffer: the current target."
  (format "DSH Bridge · target: %s" (dsh-bridge--target-label)))

(define-derived-mode dsh-bridge-view-mode special-mode "DSH-View"
  "Major mode for `*dsh-bridge-output*' and `*dsh-bridge-inbox*'.
Read-only (inherited from `special-mode'); refreshed with `g'
(`revert-buffer-function').  The letter keys mirror the `dsh-bridge'
dispatcher: `s' send, `d' draft, `f' re-fetch/re-pull, `i' pull inbox,
`S' select session, `l' list sessions.  `h' or `?' describes this mode.")

(dolist (spec dsh-bridge--verb-suffixes)
  (define-key dsh-bridge-view-mode-map (kbd (car spec)) (cadr spec)))

(defun dsh-bridge--revert-output (&rest _)
  "Re-fetch the latest reply into the output buffer."
  (dsh-bridge-fetch))

(defun dsh-bridge--revert-inbox (&rest _)
  "Re-pull bridge messages into the inbox buffer."
  (dsh-bridge-inbox))

;;; Verbs

;;;###autoload
(defun dsh-bridge-send (&optional session-id)
  "Send the region, or the whole buffer, to the DSH session as a prompt.
With a prefix argument, choose the target session for this call only, without
changing the pin.  A whole-buffer send asks for confirmation first, except in
`dsh-bridge-prompt-mode' where sending the whole buffer is the point."
  (interactive (list (dsh-bridge--read-session-override "Send to session: ")))
  (let ((whole (not (use-region-p))))
    (when (and whole
               (not (eq major-mode 'dsh-bridge-prompt-mode))
               (not (y-or-n-p (format "Send the whole %s buffer to DSH? "
                                      (buffer-name)))))
      (user-error "dsh-bridge: aborted"))
    (dsh-bridge-send-text (dsh-bridge--region-or-buffer) session-id)))

;;;###autoload
(defun dsh-bridge-draft (&optional session-id)
  "Send the region, or the whole buffer, to the DSH composer as a draft.
Like `dsh-bridge-send', but nothing is submitted; the text lands in the
composer for review.  With a prefix argument, choose the target session for
this call only."
  (interactive (list (dsh-bridge--read-session-override "Draft to session: ")))
  (dsh-bridge-send-draft (dsh-bridge--region-or-buffer) session-id))

;;;###autoload
(defun dsh-bridge-fetch (&optional session-id)
  "Fetch the latest DSH assistant reply into *dsh-bridge-output*.
With a prefix argument, fetch from a chosen session for this call only.
`g' or `f' in the output buffer re-fetches."
  (interactive (list (dsh-bridge--read-session-override "Fetch from session: ")))
  (dsh-bridge--call "GET"
                    (dsh-bridge--path "/output"
                                      (or session-id dsh-bridge-target-session))
                    nil
    (lambda (status body http-status)
      (let* ((alist (condition-case nil
                        (json-parse-string body :object-type 'alist)
                      (error nil)))
             (err (dsh-bridge--error-message status http-status alist)))
        (cond
         (err (message "dsh-bridge: %s" err))
         (t
          (with-current-buffer (get-buffer-create "*dsh-bridge-output*")
            (unless (eq major-mode 'dsh-bridge-view-mode)
              (dsh-bridge-view-mode))
            (setq-local revert-buffer-function #'dsh-bridge--revert-output)
            (setq-local dsh-bridge--view-content-session
                        (or (alist-get 'sessionId alist)
                            session-id dsh-bridge-target-session))
            (setq-local dsh-bridge--view-timestamp
                        (format-time-string "%H:%M:%S"))
            (setq header-line-format (dsh-bridge--view-header-line))
            (let ((inhibit-read-only t))
              (erase-buffer)
              (insert (or (cdr (assoc 'text alist)) ""))
              (goto-char (point-min))))
          (pop-to-buffer "*dsh-bridge-output*")
          (message "dsh-bridge: fetched reply from %s"
                   (or (dsh-bridge--label-from-response
                        alist (alist-get 'sessionId alist))
                       "last-active session"))))))))

;;;###autoload
(defun dsh-bridge-inbox ()
  "Pull DSH→Emacs messages into *dsh-bridge-inbox*, acking after success.
Entries are acked only after they are inserted, so a crash between the insert
and the ack redelivers them on the next pull (duplicates, not loss).
`g' or `i' in the inbox buffer re-pulls."
  (interactive)
  (let* ((result (dsh-bridge--request "GET" "/outbox" nil))
         (status (car result))
         (alist (cdr result)))
    (cond
     ((null status)
      (message "dsh-bridge: request failed (is `dsh web' running?)"))
     ((>= status 400)
      (message "dsh-bridge: %s"
               (or (alist-get 'error alist) (format "HTTP %s" status))))
     (t
      (let ((entries (alist-get 'entries alist))
            (overflowed (alist-get 'overflowed alist)))
        (when entries
          (with-current-buffer (get-buffer-create "*dsh-bridge-inbox*")
            (unless (eq major-mode 'dsh-bridge-view-mode)
              (dsh-bridge-view-mode))
            (setq-local revert-buffer-function #'dsh-bridge--revert-inbox)
            (setq-local dsh-bridge--view-timestamp
                        (format-time-string "%H:%M:%S"))
            (setq header-line-format (dsh-bridge--view-header-line))
            (let ((inhibit-read-only t))
              (dolist (entry entries)
                (insert (concat (dsh-bridge--inbox-header entry) "\n"))
                (insert (or (alist-get 'text entry) ""))
                (insert "\n\n"))
              (goto-char (point-min))))
          ;; Ack only after the insert above succeeded.
          (dsh-bridge--request "POST" "/outbox/ack"
                               `((ids . ,(mapcar (lambda (e) (alist-get 'id e)) entries)))))
        (message "dsh-bridge: pulled %d message%s%s"
                 (length entries)
                 (if (= (length entries) 1) "" "s")
                 (if overflowed " (overflow — some dropped)" ""))
        (when entries (pop-to-buffer "*dsh-bridge-inbox*")))))))

;;;###autoload
(defun dsh-bridge-prompt ()
  "Pop to the persistent prompt-editing buffer `*dsh-bridge-prompt*'.
The text survives sends, so a prompt can be edited and resubmitted; `C-c C-k'
erases the buffer."
  (interactive)
  (let ((buffer (get-buffer-create "*dsh-bridge-prompt*")))
    (with-current-buffer buffer
      (unless (eq major-mode 'dsh-bridge-prompt-mode)
        (dsh-bridge-prompt-mode)))
    (pop-to-buffer buffer)))

;;; The prompt buffer

(defun dsh-bridge--prompt-mode-setup ()
  "Common setup for `dsh-bridge-prompt-mode'."
  (setq-local header-line-format (dsh-bridge--prompt-header-line)))

(declare-function markdown-mode "markdown-mode")
(declare-function dsh-bridge-prompt-mode "dsh-bridge")

(defmacro dsh-bridge--define-prompt-mode (parent)
  "Define `dsh-bridge-prompt-mode' as a variant of PARENT.
PARENT is `markdown-mode' or `text-mode', chosen at load time: the mode is
defined once, with a literal symbol parent.  A conditional expression cannot
go directly in the parent slot of `define-derived-mode' — the macro quotes it
into the mode metadata and the docstring generation calls `symbol-name' on it
— so the choice is resolved here, driven by `dsh-bridge-prompt-markdown' and
`(require \\='markdown-mode nil t)'."
  `(define-derived-mode dsh-bridge-prompt-mode ,parent "DSH-Prompt"
     "Major mode for composing DSH prompts.
`C-c C-c' sends the region or whole buffer (the buffer is not cleared, so
text survives for edit-and-resubmit), `C-c C-d' pushes it as a composer
draft, `C-c C-k' erases the buffer."
     (dsh-bridge--prompt-mode-setup)))

;; The map is created by whichever branch of the `if' runs; declare it here so
;; the byte-compiler knows the `define-key' forms below are valid.
(defvar dsh-bridge-prompt-mode-map)

(if (and dsh-bridge-prompt-markdown (require 'markdown-mode nil t))
    (dsh-bridge--define-prompt-mode markdown-mode)
  (dsh-bridge--define-prompt-mode text-mode))

(define-key dsh-bridge-prompt-mode-map (kbd "C-c C-c") #'dsh-bridge-send)
(define-key dsh-bridge-prompt-mode-map (kbd "C-c C-d") #'dsh-bridge-draft)
(define-key dsh-bridge-prompt-mode-map (kbd "C-c C-k") #'dsh-bridge-erase-prompt)

(defun dsh-bridge-erase-prompt ()
  "Erase the contents of the prompt buffer."
  (interactive)
  (erase-buffer))

;;; Session targeting

(defun dsh-bridge-current-session ()
  "Message the DSH session the bridge currently targets."
  (interactive)
  (let* ((result (dsh-bridge--request "GET" "/current" nil))
         (status (car result))
         (alist (cdr result))
         (session-id (and alist (alist-get 'sessionId alist))))
    (cond
     ((null status)
      (message "dsh-bridge: request failed (is `dsh web' running?)"))
     ((>= status 400)
      (message "dsh-bridge: %s"
               (or (and alist (alist-get 'error alist))
                   (format "HTTP %s" status))))
     (session-id
      (setq dsh-bridge-target-session session-id)
      (message "dsh-bridge: targeting session %s"
               (or (dsh-bridge--label-for-id session-id) session-id)))
     (t
      (setq dsh-bridge-target-session nil)
      (message "dsh-bridge: targeting the last-active session")))))

(make-obsolete 'dsh-bridge-current-session
               "the `dsh-bridge' dispatcher header shows the current target"
               "0.1.0")

(defun dsh-bridge--refresh-view-headers ()
  "Refresh header lines of live bridge buffers after a retarget."
  (dolist (name '("*dsh-bridge-output*" "*dsh-bridge-inbox*"))
    (when (buffer-live-p (get-buffer name))
      (with-current-buffer (get-buffer name)
        (when (eq major-mode 'dsh-bridge-view-mode)
          (setq header-line-format (dsh-bridge--view-header-line))))))
  (when (buffer-live-p (get-buffer "*dsh-bridge-prompt*"))
    (with-current-buffer "*dsh-bridge-prompt*"
      (when (eq major-mode 'dsh-bridge-prompt-mode)
        (setq header-line-format (dsh-bridge--prompt-header-line))))))

;;;###autoload
(defun dsh-bridge-select-session (session-id)
  "Set the DSH session the bridge targets to SESSION-ID.
SESSION-ID is a session id string, or nil to target the last-active session."
  (interactive
   (list
    (let* ((choices (dsh-bridge--live-session-choices))
           (choice (completing-read "Target session: "
                                    (append choices '(("(last-active)" . nil)))
                                    nil t)))
      (if (string= choice "(last-active)") nil
        (cdr (assoc choice choices))))))
  (let* ((result (dsh-bridge--request "POST" "/select"
                  (if session-id
                      `((sessionId . ,session-id))
                    '((sessionId . :json-null)))))
         (status (car result))
         (alist (cdr result)))
    (cond
     ((null status)
      (message "dsh-bridge: request failed (is `dsh web' running?)"))
     ((>= status 400)
      (message "dsh-bridge: %s"
               (or (alist-get 'error alist) (format "HTTP %s" status))))
     ((and alist (assoc 'error alist))
      (message "dsh-bridge: %s" (alist-get 'error alist)))
     (t
      (setq dsh-bridge-target-session session-id)
      (dsh-bridge--refresh-view-headers)
      (dsh-bridge--refresh-sessions-buffer)
      (message "dsh-bridge: targeting %s"
               (or (and session-id
                        (or (dsh-bridge--label-for-id session-id) session-id))
                   "last-active session"))))))

;;; The sessions buffer

(defface dsh-bridge-current-target-face
  '((t :inherit bold :foreground "ForestGreen"))
  "Face for the currently pinned session in `*dsh-bridge-sessions*'."
  :group 'dsh-bridge)

(defun dsh-bridge--session-cell (session)
  "Session label cell for SESSION, marked when it is the pinned target."
  (let ((label (dsh-bridge--session-label session)))
    (if (equal (alist-get 'id session) dsh-bridge-target-session)
        (propertize (format "▶ %s" label) 'face 'dsh-bridge-current-target-face)
      label)))

(defun dsh-bridge--age-sorter (a b)
  "Sort predicate for the Age column: ascending by activity timestamp.
A and B are `tabulated-list' entries (ID COLS); the Age cell is a string
carrying the raw ms-epoch timestamp in its `dsh-bridge-age-ts' text property."
  (let* ((n (seq-position tabulated-list-format "Age"
                           (lambda (e elt) (equal (car e) elt))))
         (ta (get-text-property 0 'dsh-bridge-age-ts (aref (cadr a) n)))
         (tb (get-text-property 0 'dsh-bridge-age-ts (aref (cadr b) n))))
    (< ta tb)))

(defun dsh-bridge--session-entry (session)
  "Return a `tabulated-list' entry (ID . COLS) for SESSION (a row alist)."
  (let* ((id (alist-get 'id session))
         (live (alist-get 'live session))
         (activity (dsh-bridge--session-activity session))
         (age (propertize (dsh-bridge--relative-age activity)
                          'dsh-bridge-age-ts activity))
         (cols (vector (dsh-bridge--session-cell session)
                       (if live "live" "saved")
                       (or (alist-get 'cwd session) "")
                       age)))
    (when dsh-bridge-show-session-ids
      (setq cols (vconcat cols (vector id))))
    (list id cols)))

(define-derived-mode dsh-bridge-sessions-mode tabulated-list-mode "DSH-Sessions"
  "Major mode for browsing DSH sessions.
`RET' pins the session under point (live only), `u' unpins, `p' pins and pops
to the prompt buffer, `f' peeks the session's latest reply without changing
the pin, `w' copies the session id under point, `D' describes the session,
`g' re-fetches the list, `S' sorts by column.")

(define-key dsh-bridge-sessions-mode-map (kbd "RET")
            #'dsh-bridge-select-session-at-point)
(define-key dsh-bridge-sessions-mode-map (kbd "u")
            #'dsh-bridge-unpin-session)
(define-key dsh-bridge-sessions-mode-map (kbd "p")
            #'dsh-bridge-select-session-at-point-and-prompt)
(define-key dsh-bridge-sessions-mode-map (kbd "f")
            #'dsh-bridge-peek-session)
(define-key dsh-bridge-sessions-mode-map (kbd "w")
            #'dsh-bridge-copy-session-id)
(define-key dsh-bridge-sessions-mode-map (kbd "D")
            #'dsh-bridge-describe-session)

(defun dsh-bridge-select-session-at-point ()
  "Select the DSH session shown on the current line of the session list."
  (interactive)
  (let ((id (tabulated-list-get-id)))
    (when id
      (if (equal (aref (tabulated-list-get-entry) 1) "live")
          (dsh-bridge-select-session id)
        (message "dsh-bridge: session %s is not live"
                 (or (dsh-bridge--label-for-id id) id))))))

(defun dsh-bridge-unpin-session ()
  "Unpin the target session (the bridge targets the last-active session)."
  (interactive)
  (dsh-bridge-select-session nil))

(defun dsh-bridge-select-session-at-point-and-prompt ()
  "Pin the session under point and pop to `*dsh-bridge-prompt*'."
  (interactive)
  (let ((id (tabulated-list-get-id)))
    (if (and id (equal (aref (tabulated-list-get-entry) 1) "live"))
        (progn
          (dsh-bridge-select-session id)
          (dsh-bridge-prompt))
      (message "dsh-bridge: session %s is not live"
               (or (dsh-bridge--label-for-id id) id)))))

(defun dsh-bridge-peek-session ()
  "Fetch the session under point's latest reply into *dsh-bridge-output*.
The pin is not changed: this is a one-shot fetch, like `C-u
dsh-bridge-fetch'."
  (interactive)
  (let ((id (tabulated-list-get-id)))
    (if id
        (dsh-bridge-fetch id)
      (message "dsh-bridge: no session under point"))))

(defun dsh-bridge-copy-session-id ()
  "Copy the raw DSH session id under point to the kill ring."
  (interactive)
  (let ((id (tabulated-list-get-id)))
    (if id
        (progn
          (kill-new id)
          (message "dsh-bridge: copied session id %s" id))
      (message "dsh-bridge: no session under point"))))

(defun dsh-bridge-describe-session ()
  "Show details of the session under point, including its raw id."
  (interactive)
  (let ((id (tabulated-list-get-id)))
    (if (not id)
        (message "dsh-bridge: no session under point")
      (let* ((session (dsh-bridge--session-for-id id))
             (buffer (get-buffer-create "*dsh-bridge-session-details*")))
        (with-current-buffer buffer
          (let ((inhibit-read-only t))
            (erase-buffer)
            (insert (format "Session id:   %s\n" id))
            (when session
              (insert (format "Label:        %s\n"
                              (dsh-bridge--session-label session)))
              (insert (format "State:        %s\n"
                              (if (alist-get 'live session) "live" "saved")))
              (insert (format "Directory:    %s\n"
                              (or (alist-get 'cwd session) "")))
              (let ((ts (or (alist-get 'lastActive session)
                            (alist-get 'createdAt session))))
                (insert (format "Last active:  %s\n"
                                (if ts (format-time-string "%Y-%m-%d %H:%M:%S"
                                                           (/ ts 1000))
                                  "")))))
            (goto-char (point-min))))
        (with-current-buffer buffer
          (special-mode))
        (pop-to-buffer buffer)))))

(defun dsh-bridge--list-sessions-in-buffer ()
  "Fill `*dsh-bridge-sessions*' with the current session list.
Returns non-nil when sessions were listed."
  (let ((sessions (dsh-bridge--fetch-sessions)))
    (if (null sessions)
        nil
      (with-current-buffer (get-buffer-create "*dsh-bridge-sessions*")
        (dsh-bridge-sessions-mode)
        ;; Override tabulated-list's re-print-only revert: `g' must re-fetch
        ;; the session list from the host.
        (setq-local revert-buffer-function
                    (lambda (&rest _) (dsh-bridge--list-sessions-in-buffer)))
        (setq tabulated-list-format
              (let ((format [("Session" 45 t)
                             ("State" 8 t)
                             ("Cwd" 40 t)
                             ("Age" 12 dsh-bridge--age-sorter)]))
                (if dsh-bridge-show-session-ids
                    (vconcat format [("Id" 40 t)])
                  format)))
        (setq tabulated-list-sort-key '("Age" . t))
        (setq tabulated-list-entries
              (mapcar #'dsh-bridge--session-entry sessions))
        (tabulated-list-init-header)
        (tabulated-list-print))
      t)))

(defun dsh-bridge--refresh-sessions-buffer ()
  "Re-render `*dsh-bridge-sessions*' in place if it is live."
  (when (buffer-live-p (get-buffer "*dsh-bridge-sessions*"))
    (with-current-buffer "*dsh-bridge-sessions*"
      (when (eq major-mode 'dsh-bridge-sessions-mode)
        (dsh-bridge--list-sessions-in-buffer)))))

;;;###autoload
(defun dsh-bridge-list-sessions ()
  "List DSH sessions in a tabulated buffer.
In the session list: `RET' pins the session under point (live only), `u'
unpins, `p' pins and pops to the prompt buffer, `f' peeks the session's
latest reply without changing the pin, `w' copies the session id, `D' shows
session details, `g' re-fetches, `S' sorts by column."
  (interactive)
  (if (dsh-bridge--list-sessions-in-buffer)
      (pop-to-buffer "*dsh-bridge-sessions*")
    (message "dsh-bridge: no sessions (or request failed)")))

;;; The dispatcher

;;;###autoload
(transient-define-prefix dsh-bridge ()
  "Dispatch DSH bridge actions.
The header shows the current target session; the verbs act on it.  `s' sends
the region or buffer as a prompt, `d' sends it as a draft, `p' opens the
prompt buffer, `f' fetches the latest reply, `i' pulls the inbox, `S' selects
the target session, `l' lists sessions."
  dsh-bridge--dispatcher-layout)

;;; Menu bar (under Tools)

(defvar dsh-bridge-menu
  (easy-menu-create-menu
   "DSH Bridge"
   '(["DSH Bridge Dispatcher…" dsh-bridge
      :help "Open the DSH bridge dispatcher"]
     "---"
     ["Edit Prompt Buffer" dsh-bridge-prompt
      :help "Pop to the persistent prompt buffer"]
     ["Send Region or Buffer" dsh-bridge-send
      :help "Send the region (or whole buffer) to DSH as a prompt"]
     ["Send as Draft" dsh-bridge-draft
      :help "Send the region (or whole buffer) to the DSH composer as a draft"]
     ["Fetch Latest Reply" dsh-bridge-fetch
      :help "Fetch the latest assistant reply into *dsh-bridge-output*"]
     ["Pull Inbox" dsh-bridge-inbox
      :help "Pull Send-to-Emacs messages into *dsh-bridge-inbox*"]
     "---"
     ["Select Session…" dsh-bridge-select-session
      :help "Pin the target session (or choose last-active to unpin)"]
     ["List Sessions" dsh-bridge-list-sessions
      :help "Browse DSH sessions in a tabulated list"]))
  "DSH Bridge menu, installed under Tools.")

(easy-menu-add-item nil '("Tools") dsh-bridge-menu)

;;; Back-compat: the pre-interface command names, obsolete for one cycle.

(define-obsolete-function-alias 'dsh-bridge-send-region 'dsh-bridge-send "0.1.0")
(define-obsolete-function-alias 'dsh-bridge-send-buffer 'dsh-bridge-send "0.1.0")
(define-obsolete-function-alias 'dsh-bridge-get-output 'dsh-bridge-fetch "0.1.0")
(define-obsolete-function-alias 'dsh-bridge-pull-inbox 'dsh-bridge-inbox "0.1.0")
(define-obsolete-function-alias 'dsh-bridge-send-draft-region 'dsh-bridge-draft "0.1.0")
(define-obsolete-function-alias 'dsh-bridge-send-draft-buffer 'dsh-bridge-draft "0.1.0")

(provide 'dsh-bridge)
;;; dsh-bridge.el ends here
